### ISSUE TITLE
ARU Org Join Request

### ISSUE THREAD

**Issue by Heather-Wimberley** [African-Robotics-Unit/.github#14]
### Your Name

Heather Wimberley

### Membership Type

Member

### Role

Postgraduate

### Supervisor

Amir Patel, Stacey Shield

### Teams

Student

### Code of Conduct

- [X] I agree.

### Email Address Confirmation

- [X] I confirm that I have read and understood the above.

**Comment by LawrenceStanton** [comment]
Annyeonghaseyo
