### ISSUE TITLE
ARU Org Join Request

### ISSUE THREAD

**Issue by fnndyl-UCT** [African-Robotics-Unit/.github#15]
### Your Name

Dylan Fanner

### Membership Type

Member

### Role

Postgraduate

### Supervisor

Other

### Code of Conduct

- [X] I agree.

### Email Address Confirmation

- [X] I confirm that I have read and understood the above.

**Comment by LawrenceStanton** [comment]
Apologies for delay. Invite sent. Please accept and you'll be added to the ARU Org.
