### ISSUE TITLE
ARU Org Join Request

### ISSUE THREAD

**Issue by ZubairMartin** [African-Robotics-Unit/.github#17]
### Your Name

Zubair Martin

### Membership Type

Member

### Role

Postgraduate

### Supervisor

Amir Patel

### Teams

I would like to access all repos related to Baleka II (including shunt regulator, Pyomoschool, hopper controller and Kemba - simulation (view)).

### Code of Conduct

- [X] I agree.

### Email Address Confirmation

- [X] I confirm that I have read and understood the above.

**Comment by LawrenceStanton** [comment]
Invite sent.

Remember to please be assigned the required permissions for the repositories you require by the owners of those repositories.
