### ISSUE TITLE
ARU Org Join Request

### ISSUE THREAD

**Issue by damienschutz** [African-Robotics-Unit/.github#18]
### Your Name

Damien Schütz

### Membership Type

Member

### Role

Postgraduate

### Supervisor

Amir Patel, Stacey Shield

### Teams

The learning docs page

### Code of Conduct

- [X] I agree.

### Email Address Confirmation

- [X] I confirm that I have read and understood the above.

**Comment by LawrenceStanton** [comment]
Invite Sent
