### ISSUE TITLE
ARU Org Join Request

### ISSUE THREAD

**Issue by ghost** [African-Robotics-Unit/.github#19]
### Your Name

Robyn Verrinder

### Membership Type

Member

### Role

Staff

### Supervisor

Robyn Verrinder

### Teams

@SHARC

### Code of Conduct

- [X] I agree.

### Email Address Confirmation

- [X] I confirm that I have read and understood the above.

**Comment by LawrenceStanton** [comment]
@robynverrinderUCT are you sure you want to make another GitHub account for UCT? I see you already have @robynverrinder. If it's a simple matter of emails you can add multiple.
